### ISSUE TITLE
Map.swift:53:26: Use of undeclared type 'NSNull'

### ISSUE THREAD

**Issue by jplasser** [LoganWright/Genome#20] opened 2015-10-16 21:12 UTC
I opened the playground folder in Xcode 7.0.1 and got the following error:
Genome/Genome.playground/Sources/Map.swift:53:26: Use of undeclared type ‚NSNull'

**Comment by LoganWright** [comment] 2015-10-18 21:26
Hi @jplasser 

Thank you for checking out the library and letting me know about the problem, it makes it a lot easier to fix this sort of stuff!

Can I ask when you last pulled the library, I merged in an update a few days ago that addresses the `NSNull` issue.

f5cca7

If you're still having the same problem on the latest version, can you give me some reproduce steps so I can address it?

Best,

Logan

**Comment by LoganWright** [comment] 2015-10-18 22:51
@jplasser 

I realize now that by fixing the NSNull issue, I created another because NSNull is foundation dependent.  I've created a workaround for the issue that should solve both situations, at least in the interim.

Again, thank you for notifying me!

Best,

Logan

**Closed by LoganWright** 2015-10-18 22:51 UTC
Labels: bug

**Comment by jplasser** [comment] 2015-10-19 05:34
Great! I pulled from Master. I tried to solve the dependency myself, but had no idea. Thanks for your time and solving this issue!

Best,
Jürgen
